services:
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./django:/django
    #   - /django/digital_twin/static
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
      - digital_twin
    restart: always
  frontend:
    build: ./frontend
    command: npm run start
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - SERVER_API_URL=http://django:8000
    ports:
      - "3005:3005"
    # volumes:
    #   - ./frontend:/frontend
    #   - /frontend/node_modules # <-- creates the node_modules in frontend path
    #   - /frontend/.next # <-- creates the .next folder in frontend path
    depends_on:
      - django
    networks:
      - digital_twin
    restart: always
  
networks:
  digital_twin:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
 