volumes:
  local_postgres_data: {}

services:
  postgres:
    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3005:3005"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - postgres
      - django
