volumes:
  local_postgres_data: {}

services:
  postgres:
    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
  #  frontend:
  #   container_name: frontend
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   networks:
  #     - core
  #   command:
  #     "npm run dev"
  #   volumes:
  #     - ./frontend:/frontend
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - node-modules:/frontend/node_modules
  #   ports:
  #     - 3010:3010
  #   links:
  #     - backend:backend