services:
  django:
    build: ./django
    command: gunicorn digital_twin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - django_static:/django/digital_twin/static
      - django_media:/django/digital_twin/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
      - digital_twin
    restart: always
  frontend:
    build: ./frontend
    command: npm run start
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - SERVER_API_URL=http://django:8000
    ports:
      - "3005:3005"
    depends_on:
      - django
    networks:
      - digital_twin
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      - django_static:/nginx/static
      - django_media:/nginx/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - digital_twin
    restart: unless-stopped

volumes:
  django_static:
  django_media:
  
networks:
  digital_twin:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
 